twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        '%kernel.project_dir%/public': public

when@test:
    twig:
        strict_variables: true
        form_theme: ['bootstrap_5_layout.html.twig']
